schoolinfra/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Redirect to app called schoolmanagement
    url(r'^', include("schoolmanagement.urls")),
    url(r'^principal/', include("principal.urls")),
    url(r'^teacher/', include('teachers.urls')),
    url(r'^student/', include('students.urls')),
]

students/urls.py
from django.conf.urls import include, url


app_name = 'students'

from .views import Add_Student, studentloggedin, LoginStudent, studentloggedout

urlpatterns = [
    # Redirect to Home Page
    url(r'^add/', Add_Student.as_view(), name='addstudent'),
    url(r'^login/', LoginStudent.as_view(), name='studentlogin'),
    url(r'^loggedin/', studentloggedin, name='studentloggedin'),
    url(r'^logout/', studentloggedout, name='studentloggedout'),

]

teachers/urls.py
from django.conf.urls import url
from .views import LoginTeacher,add_teacher,all_teacher_details, teacherloggedout,teacherloggedin

app_name = 'teachers'

urlpatterns = [
    # Redirect to Home Page
    url(r'add/$', add_teacher, name="addTeacher"),
    url(r'details/$', all_teacher_details, name="details"),
    url(r'login/$', LoginTeacher.as_view(), name='teacherlogin'),
    url(r'profile/$', teacherloggedin, name='teacherprofile'),
    url(r'^logout/', teacherloggedout, name='teacherloggedout'),

]

teachers/models.py
## order of clean imports
## A good practise 


## 1. standard lib imports

## 2. core django imports
## 3. third party imports


from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from principal.models import Principal


# Create your models here.


class Teacher(models.Model):
    teacher_name = models.CharField(max_length=100)
    teacher_subject = models.CharField(max_length=50)
    teacher_age = models.CharField(max_length=100)
    # principal = models.ForeignKey(Principal)
    timestamp = models.DateTimeField(auto_now_add=True)
    # user = models.OneToOneField(User)
    teacher_pic = models.ImageField(null=True, blank=True)  ##Let us write a common function for this file upload ###

    # slug = models.SlugField()

    # def get_absolute_url(self):
    #     return reverse('#',kwargs={'pk':self.pk})

    # def save(self, *args, **kwargs):
    # 	if not self.slug:
    # 		self.slug = slugify(teacher_name)
    # 	save(Teacher, self).save(*args, **args)


    def get_absolute_url(self):
        pass

    def __unicode__(self):
        return self.teacher_name + '---' + self.teacher_subject + '---' + self.teacher_age

    def __str__(self):
        return self.teacher_name + '---' + self.teacher_subject + '---' + self.teacher_age

teachers/forms.py
from django import forms

from .models import Teacher

class TeacherForm(forms.ModelForm):

	class Meta:
		model = Teacher
		fields = ['teacher_age']

class TeacherLoginForm(forms.Form):
	username = forms.CharField(max_length=20)
	password = forms.CharField(widget=forms.PasswordInput)

teachers/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.contrib.auth import authenticate,login
from django.http import HttpResponseRedirect



from .models import Teacher
from schoolmanagement.forms import TeacherForm
from .forms import TeacherLoginForm



# Create your views here.
def add_teacher(request):
    form = TeacherForm(request.POST or None)
    if form.is_valid():
        # new_teacher = form.save(commit=False)
        form.save()
        return render(request, 'teachers/teachers_details.html', {})

    context = {
        "form": form,
    }
    return render(request, 'teachers/teachers_form.html', context)


def all_teacher_details(request):
    # teacher = get_object_or_404(Teacher)
    all_teacher = Teacher.objects.all()
    return render(request, 'teachers/teachers_details.html', {'all_teacher': all_teacher})


class Add_Teacher(View):

    def get(self, request, *args, **kwargs):
        userform = UserRegistrationForm()
        teacherform = TeacherForm()

        return render(request,'teachers/addteacher.html',{'userform':userform, 'teacherform':teacherform})

    def post(self, request, *args, **kwargs):
        userform = UserRegistrationForm(request.POST)
        teacherform = TeacherForm(request.POST)

        if userform.is_valid and teacherform.is_valid:
            u = userform.save(commit=False)
            teacherform.user = u.id
            teacherform.save()
            u.save()

            return HttpResponseRedirect(reverse('schoolmanagement:thanks'))
        
        return render('students/addstudent.html',{'userform':userform, 'studentform':studenform})


class LoginTeacher(View):

    def get(self, request, *args, **kwargs):
        f = TeacherLoginForm()
        return render (request, 'teachers/teacherloginform.html', {'f':f})

    def post(self, request, *args, **kwargs):
        f = TeacherLoginForm(request.POST or None)
        if f.is_valid():
            username = f.cleaned_data['username']
            password = f.cleaned_data['password']
        #@  print request.user
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
        #       print request.user
         #       user = request.user
                return HttpResponseRedirect('/teacher/profile/')  
        return render (request, 'teachers/teacherloginform.html', {'f':f})

def teacherloggedin(request):
    return render(request, 'teachers/teacherprofile.html')

def teacherloggedout(request):
    return render(request, 'teachers/teacherloggedout.html')

teachers/templates/teachers/teacherloggedout.html
<h1>teacher is loggedout</h1>

teachers/templates/teachers/teacherloginform.html
{% load crispy_forms_tags %}
<form action="{%url 'teachers:teacherlogin' %}" method="post">
{% csrf_token %}
{{f| crispy}}
<input type="submit" value="Submit" />
</form>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

teachers/templates/teachers/teacherprofile.html
<h1>Teacher are logged in ass {{request.user}}</h1>

teachers/templates/teachers/teachers_details.html
{% extends 'schoolmanagement/base.html' %}
{% block title %}All Teachers{% endblock %}

{% block body %}
    <div class="container-fluid teachers-container">
        <div class="row">
            <div class="col-sm-8 col-md-9">

                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation" class="active"><a href="{% url 'teachers:details' %}">View All</a></li>

                </ul>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>All Teachers</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Teacher Name</th>
                                <th>Teacher Subject</th>
                                <th>Teacher Age</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for teacher in all_teacher %}
                                <tr>
                                    <td>{{ teacher.teacher_name }}</td>
                                    <td>{{ teacher.teacher_subject }}</td>
                                    <td>{{ teacher.teacher_age }}</td>

                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>


            </div>
        </div>
    </div>



{% endblock %}

teachers/templates/teachers/teachers_form.html
{% extends 'schoolmanagement/base.html' %}
{% block title %}Add a New Teacher{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Teacher</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'schoolmanagement/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>



    </div>

</div>
{% endblock %}