principal/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'principal'

urlpatterns = [
    # Redirect to Home Page
    url(r'^$', views.as_principal, name="principal"),
    # url(r'teacher/add/$', views.add_teacher, name="addTeacher"),
    url(r'teacher/add/$', include('teachers.urls')),
    url(r'login$', views.login_view, name="login"),
    url(r'logout$', views.logout_view, name="logout"),
]

schoolinfra/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Redirect to app called schoolmanagement
    url(r'^', include("schoolmanagement.urls")),
    url(r'^principal/', include("principal.urls")),
    url(r'^teacher/', include('teachers.urls')),
    url(r'^student/', include('students.urls')),
]

students/urls.py
from django.conf.urls import include, url


app_name = 'students'

from .views import Add_Student, studentloggedin, LoginStudent, studentloggedout

urlpatterns = [
    # Redirect to Home Page
    url(r'^add/', Add_Student.as_view(), name='addstudent'),
    url(r'^login/', LoginStudent.as_view(), name='studentlogin'),
    url(r'^loggedin/', studentloggedin, name='studentloggedin'),
    url(r'^logout/', studentloggedout, name='studentloggedout'),

]

teachers/urls.py
from django.conf.urls import url
from .views import LoginTeacher,add_teacher,all_teacher_details, teacherloggedout,teacherloggedin

app_name = 'teachers'

urlpatterns = [
    # Redirect to Home Page
    url(r'add/$', add_teacher, name="addTeacher"),
    url(r'details/$', all_teacher_details, name="details"),
    url(r'login/$', LoginTeacher.as_view(), name='teacherlogin'),
    url(r'profile/$', teacherloggedin, name='teacherprofile'),
    url(r'^logout/', teacherloggedout, name='teacherloggedout'),

]

principal/models.py
## order of clean imports
## A good practise 


## 1. standard lib imports

## 2. core django imports
## 3. third party imports

## 4. local imports


from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Principal(models.Model):
    princy_name = models.CharField(max_length=100)
    princy_age = models.IntegerField()
    user = models.OneToOneField(User)
    princy_pic = models.ImageField(null=True, blank=True)

    def __unicode__(self):
    	return self.princy_name

    def __str__(self):
        return self.princy_name

principal/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from schoolmanagement.forms import (TeacherForm, UserLoginForm)
from teachers.models import Teacher
from django.contrib.auth import (authenticate, login, logout, get_user_model)


# Create your views here.
def as_principal(request):
    return render(request, 'principal/principal.html', {})


def add_teacher(request):
    form = TeacherForm(request.POST or None)
    if form.is_valid():
        # new_teacher = form.save(commit=False)
        form.save()
        return
        # teacher_name = request.POST.get('teacher_name')
        # teacher_subject = request.POST.get('teacher_subject')
        # age = request.POST.get('teacher_age')
        # data_add_teacher = Teacher(teacher_name=teacher_name, teacher_subject=teacher_subject, teacher_age=age)
        # data_add_teacher.save()

    context = {
        "form": form,
    }
    return render(request, 'teachers/teachers_form.html', context)


def login_view(request):
    '''
    Login form for Princial as of now only
    :param request:
    :return:
    '''
    # if request.user.is_authenticated():
    #     return redirect('principal',{})

    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        print(request.user.is_authenticated())
        return render(request, 'principal/principal.html', {})
    return render(request, 'principal/login_form.html', {"form": form})


def logout_view(request):
    '''
    When User logged out redirect to homepage
    :param request:
    :return:
    '''
    logout(request)
    form = UserLoginForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'schoolmanagement/index.html', {})

principal/templates/principal/login_form.html
{% extends 'schoolmanagement/base_0.html' %} }
{% block title %}Admin Login{% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'principal:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}

principal/templates/principal/principal.html
{% extends 'schoolmanagement/base.html' %} }
{% block title %}Home{% endblock %}
{% block body %}
    <strong> Welcome Principal</strong>
    <ul>
        <li>
            {% comment %}// TODO: future maintenance, add form of different app from context app.{% endcomment %}
            {#            <a href="{% url 'principal:addTeacher' %}">Add teacher</a>#}
            <a href="{% url 'teachers:addTeacher' %}">Add teacher</a>
        </li>

    </ul>
{% endblock %}