principal/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'principal'

urlpatterns = [
    # Redirect to Home Page
    url(r'^$', views.as_principal, name="principal"),
    # url(r'teacher/add/$', views.add_teacher, name="addTeacher"),
    url(r'teacher/add/$', include('teachers.urls')),
    url(r'login$', views.login_view, name="login"),
    url(r'logout$', views.logout_view, name="logout"),
]

schoolinfra/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Redirect to app called schoolmanagement
    url(r'^', include("schoolmanagement.urls")),
    url(r'^principal/', include("principal.urls")),
    url(r'^teacher/', include('teachers.urls')),
    url(r'^student/', include('students.urls')),
]

schoolmanagement/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'schoolmanagement'

urlpatterns = [
    # Redirect to Home Page
    url(r'^$', views.index, name="index"),
    url(r'^thanks/$', views.index, name="thanks"),

]

students/urls.py
from django.conf.urls import include, url


app_name = 'students'

from .views import Add_Student, studentloggedin, LoginStudent, studentloggedout

urlpatterns = [
    # Redirect to Home Page
    url(r'^add/', Add_Student.as_view(), name='addstudent'),
    url(r'^login/', LoginStudent.as_view(), name='studentlogin'),
    url(r'^loggedin/', studentloggedin, name='studentloggedin'),
    url(r'^logout/', studentloggedout, name='studentloggedout'),

]

teachers/urls.py
from django.conf.urls import url
from .views import LoginTeacher,add_teacher,all_teacher_details, teacherloggedout,teacherloggedin

app_name = 'teachers'

urlpatterns = [
    # Redirect to Home Page
    url(r'add/$', add_teacher, name="addTeacher"),
    url(r'details/$', all_teacher_details, name="details"),
    url(r'login/$', LoginTeacher.as_view(), name='teacherlogin'),
    url(r'profile/$', teacherloggedin, name='teacherprofile'),
    url(r'^logout/', teacherloggedout, name='teacherloggedout'),

]

schoolmanagement/models.py
from django.db import models


# Create your models here.

schoolmanagement/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import (authenticate, login, logout, get_user_model)

from principal.models import Principal
from teachers.models import Teacher
from students.models import Student



class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['teacher_name', 'teacher_subject', 'teacher_age']


User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        # user_queryset = User.objects.filter(username=username)
        # if user_queryset.count() == 1:
        #     user = user_queryset.first()
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This User doesn't exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password")
            if not user.is_active:
                raise forms.ValidationError("User is not active")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

schoolmanagement/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    '''
    Function return index.html from template dir
    :param request:
    :return:
    '''
    return render(request, 'schoolmanagement/index.html', {"admin_name": "schoolinfra"})


def thanks(request):
	render_to_response('schoolmanagement/thanks.html')

schoolmanagement/templates/schoolmanagement/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}School Management{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'schoolmanagement/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">'SCHOOL NAME'</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav navbar-right">

                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

schoolmanagement/templates/schoolmanagement/base_0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}School Management{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'schoolmanagement/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'schoolmanagement:index' %}">'SCHOOL NAME'</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                 <li>
                    <a href="{% url 'principal:logout' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'principal:login' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

schoolmanagement/templates/schoolmanagement/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2"  >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

schoolmanagement/templates/schoolmanagement/index.html
{% extends 'schoolmanagement/base_0.html' %}
{% block title %}Home{% endblock %}
{% block body %}
    {% comment %} <strong> Dummy School Management System</strong>
    <ul>
        <li>
            <a href="{% url 'principal:principal' %}">Logged in as Principal(Admin)</a>
        </li>

    </ul>{% endcomment %}

    <div class="container">

        <div class="app-header">
            <h1 class="blog-title">School Management Application!</h1>
        </div>
        <div class="col-sm-8">

        </div>
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="list-group">
                {% if not user.is_authenticated %}
                <a class="list-group-item active" href="{% url 'principal:login' %}">Login As Principal</a>
                {% else %}
                <a class="list-group-item active" href="{% url 'principal:principal' %}">'{{ admin_name|title }}' Goto Principal Page</a>
                {% endif %}
                <a class="list-group-item" href="{% url 'students:studentlogin' %}">Login As Student</a>
                <a class="list-group-item" href="{% url 'teachers:teacherlogin' %}">Login As Teacher</a>
            </div>
        </div>


    </div>
{% endblock %}

schoolmanagement/templates/schoolmanagement/thanks.html
thanks.html